spring.application.name=useronboarding

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${mySecretKey123456789012345678901234567890}
jwt.access-expiry=${JWT_ACCESS_EXPIRY}
jwt.refresh-expiry=${JWT_REFRESH_EXPIRY}

aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.region=${AWS_REGION}
aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

# AI Service (External FastAPI)
ai.service.url=${AI_SERVICE_URL:http://localhost:8000}
ai.service.timeout=40